services:
  - type: web
    name: file-storage-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 "run:app" --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        sync: false
